<?php include "globals/header.phtml"; 
?>
 
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->
                <a href="index.php?page=ajouterfavoris&id=<?php echo $resultatBlog->getId(); ?>">Ajouter aux favoris !</a>
                <!-- Title -->
                <h1><?php echo $resultatBlog->getTitre();?></h1>

                <!-- Author -->
                <p class="lead">
                    by <a href="#">Start Bootstrap</a>
                </p>

                <hr>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on <?php echo $resultatBlog->getDatearticle();?></p>

                <hr>

                <!-- Preview Image -->
                <img class="img-responsive" src="vues/img/<?php echo $resultatBlog->getImage()?>" alt="">

                <hr>

                <!-- Post Content -->
                <p class="lead"><?php echo $resultatBlog->getDescription();?></p>

                <hr>
                <!-- Blog Comments -->
                    <!--Success-->
                <?php if(empty($success)==false):?>
                    <?php if($success==true):?>
                        <div class="alert alert-success">
                            <p>Bravo mon pote !</p>
                        </div>
                    <?php else :?>
                        <div class="alert alert-warning">
                            <p>Problème lors de l'ajout de l'étudiant.</p>
                        </div>
                    <?php endif;?>
                <?php endif;?>
            
                    <!--Errors-->

                
                <?php if (empty($errors)== false) : ?>
                    <div class="alert alert-danger">
                    <ul>
                        <?php foreach ($errors as $key => $value):?>
                            <li><?php echo $value; ?></li>
                        <?php endforeach ;?>
                    </ul>
                    </div>
                <?php endif; ?>


                <!-- Comments Form -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form method="POST"role="form">

                        <label>Auteur</label><input type="text" name="auteur" id="auteur" value="" placeholder="auteur">
                        

                        <label>Note</label>
                        <span id="stars"></span>


                        <div class="form-group">
                            <textarea class="form-control" name="contenu" id="contenu" rows="3"></textarea >
                           
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
               

                <?php foreach ($resultatCommentaire as $key => $value):?>
                    <div class="media">
                        <a class="pull-left" href="#">
                            <img class="media-object" src="http://placehold.it/64x64" alt="">
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading"><?php echo $value->getAuteur();?>
                                <small><?php echo $value->getDateCommentaire();?></small><br>
                                <strong><?php echo $value->getNote();?></strong>
                            </h4>
                         <?php echo htmlentities($value->getContenu());?>
                        </div>
                    </div>
                <?php endforeach ;?>


                     
      
               

            </div>
            <?php include "globals/slidebar.phtml"; ?>
            <!-- Blog Sidebar Widgets Column -->
        <!-- /.row -->
        </div>

        <hr>

<?php include "globals/footer.phtml"; ?>