<?php include "globals/header.phtml"; 
?>


<div class="col-xs-12 col-sm-8">
  <p class="pull-right visible-xs">
    <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
  </p>
  <div class="jumbotron">
    <h1>Hello, world!</h1>
    <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap. Try some responsive-range viewport sizes to see it in action.</p>
  </div>
  <div class="row">
    

<?php foreach ($resultatCategories as $key => $value):?>

    <div class="col-xs-6 col-lg-4">
      <h2><?php echo $value->getTitre();?></h2>
      <p><?php echo $value->getDescription();?></p>
      <p><a class="btn btn-default" href="index.php?page=unecategorie&id=<?= $value->getId();?>" role="button">View details »</a></p>
    </div><!--/.col-xs-6.col-lg-4-->

  <?php endforeach ;?> 



    
  </div><!--/.col-xs-6.col-lg-4-->
  



</div><!--/row-->

<?php include "globals/slidebar.phtml"; ?>


 <!-- Blog Sidebar Widgets Column -->
        
        <!-- /.row -->

        <hr>

<?php include "globals/footer.phtml"; ?>