
<?php include "globals/header.phtml";?>



<div class="container">

      <form method="POST" class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
     
        <input type="text" id="inputEmail" name="login" class="form-control" placeholder="Email address">

        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password">
        
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


<?php include "globals/slidebar.phtml";?>
<?php include "globals/footer.phtml";?>