 <?php include "globals/header.phtml"; 
?>

 <div class="container">

        <!-- Jumbotron Header -->

        <!-- Title -->
        <div class="row">
            <div class="col-lg-8">
                <header class="jumbotron hero-spacer">
                    <h1>A Warm Welcome!</h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
                    <p><a class="btn btn-primary btn-large">Call to action!</a>
                    </p>
                </header>

                <hr>
                <h3>Latest Features</h3>
                <div class="row text-center">
                <?php foreach ($resultatUnecategorie as $key => $value):?>

                        <div class="col-md-6 col-sm-6 hero-feature">
                            <div class="thumbnail">
                                
                                <img class="img-responsive" src="vues/img/<?php echo $value->getImage()?>" alt="">
                            
                                
                                <div class="caption">

                                    <h3><?php echo $value->getTitre();?></h3>
                                    <p><?php echo $value->getDescription();?></p>
                                    <p>
                                        <a href="#" class="btn btn-primary">Buy Now!</a> <a href="index.php?page=article&id=<?php echo $value->getId();?>" class="btn btn-default">More Info</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                <?php endforeach ;?> 
                </div>
            </div>
        <!-- /.row -->

        <!-- Page Features -->


        <?php include "globals/slidebar.phtml"; ?>


            
    </div>
</div>


<?php include "globals/footer.phtml"; ?>